version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: logistics_project-db-1
    environment:
      POSTGRES_DB: logitrack-db
      POSTGRES_USER: logitrack_devops
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: logistics_project-redis-1
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    container_name: logistics_project-web-1
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:8000 mylogistics.wsgi:application"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: on-failure

  celery:
    build: .
    container_name: logistics_project-celery-1
    command: celery -A mylogistics worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: on-failure
  

volumes:
  postgres_data: