version: '3.8'

# ==========================================
# LOGITRACK EC2 PRODUCTION ARCHITECTURE
# ==========================================

services:
  web:
    # We use the exact image your GitHub Action pushes to ECR
    image: 344121726575.dkr.ecr.eu-west-2.amazonaws.com/swe_devops:latest
    container_name: logitrack_web
    restart: always  # Critical: Restarts if the app crashes or EC2 reboots
    env_file:
      - .env  # Tells Docker to read the .env file in the same folder
    ports:
      - "80:8000"  # Maps standard HTTP traffic (80) to Django (8000)
    command: gunicorn mylogistics.wsgi:application --bind 0.0.0.0:8000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Prevents logs from filling up the EC2 hard drive
        max-file: "3"
    depends_on:
      - worker # Ensures the worker starts alongside the web app

  worker:
    image: 344121726575.dkr.ecr.eu-west-2.amazonaws.com/swe_devops:latest
    container_name: logitrack_celery_worker
    restart: always
    env_file:
      - .env
    # Overrides the default web command to run Celery instead
    command: celery -A mylogistics worker --loglevel=info
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"